# Generated by Django 4.2.14 on 2024-11-06 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='home_location',
            field=models.URLField(blank=True, null=True),
        ),
    ]
