# Generated by Django 5.1.3 on 2025-05-26 10:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_extra_product_extras'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='city',
            field=models.CharField(blank=True, choices=[('her', 'الهير (التوصيل مجاناً)'), ('aen', 'العين (100 د.إ رسوم التوصيل)'), ('sh', 'الشويب (30 د.إ رسوم التوصيل)'), ('fq', 'الفقع (30 د.إ رسوم التوصيل )'), ('nah', 'ناهل (40 د.إ رسوم التوصيل )'), ('sw', 'سويحان (50 د.إ رسوم التوصيل)'), ('other', 'اخرى (تحدد من قبل المحل)')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator('^\\d{1,10}$'), django.core.validators.MinLengthValidator(10)]),
        ),
    ]
