# Generated by Django 5.1.3 on 2025-05-26 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_profile_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='اسم المدينة'),
        ),
        migrations.AlterField(
            model_name='city',
            name='shipping_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='رسوم التوصيل'),
        ),
    ]
