# Generated by Django 5.1.3 on 2025-06-20 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_city_name_alter_city_shipping_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('on', models.BooleanField(default=False, verbose_name='تفعيل وضع خارج الخدمة')),
            ],
        ),
    ]
