# Generated by Django 5.1.3 on 2024-12-09 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_extra_product_extras"),
        ("order", "0008_coupon"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="extras",
            field=models.ManyToManyField(
                blank=True, related_name="order_items", to="core.extra"
            ),
        ),
    ]
