# Generated by Django 5.1.3 on 2025-05-18 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_order_notes_orderitem_extras'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='extra_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
